limit_req_zone $binary_remote_addr zone=thread_limit:10m rate=90r/m;

server {
    listen 443 ssl;
    server_name forum-api.cloud;

    ssl_certificate /etc/letsencrypt/live/forum-api.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/forum-api.cloud/privkey.pem;

    location /threads {
        limit_req zone=thread_limit burst=10 nodelay;

        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        proxy_pass http://localhost:3000;
    }
}